In [2]:
users = []

In [3]:
%%time
users.extend(('Voronov', 42))

CPU times: user 12 µs, sys: 3 µs, total: 15 µs
Wall time: 19.8 µs

In [7]:
%%time
users

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 6.44 µs

['Voronov', 42]

In [6]:
# %timeit
salaries_dict = {'name': 'Masha',
                 'surname': 'Volkova',
                 'age': 25,
                 'salary': 60000,
                 'position': 'junior'}
salaries_dict

{'name': 'Masha',
 'surname': 'Volkova',
 'age': 25,
 'salary': 60000,
 'position': 'junior'}

In [10]:
users_dict = {'mvolkova': {'name': 'Masha',
                           'surname': 'Volkova',
                           'age': 25,
                           'salary': 60000,
                           'position': 'junior'},
              'pvoronov': {'name': 'Peter',
                           'surname': 'Voronov',
                           'age': 27,
                           'salary': 100000,
                           'position': 'junior'},
              'pparker':  {'name': 'Peter',
                           'surname': 'Parker',
                           'age': 35,
                           'salary': 150000,
                           'position': 'middle'},
              'akarpov':  {'name': 'Anatoly',
                           'surname': 'Karpov',
                           'age': 30,
                           'salary': 250000,
                           'position': 'senior'}}

In [11]:
import pandas as pd

In [15]:
df = pd.read_csv('../../lesson_1_data.csv', encoding='windows-1251', sep=';')
df

,Номер,Дата создания,Дата оплаты,Title,Статус,Заработано,Город,Платежная система
0,1062823,01.12.2019 10:50,01.12.2019 10:52,Курс обучения «Эксперт»,Завершен,29597.50,Чита,Сбербанк эквайринг
1,1062855,01.12.2019 20:53,01.12.2019 21:27,Курс обучения «Эксперт»,Завершен,17450.30,Краснодар,Яндекс.Касса
2,1062856,01.12.2019 21:43,NaN,Курс обучения «Специалист»,Отменен,0.00,NaN,NaN
3,1062880,03.12.2019 0:18,NaN,Курс обучения «Консультант»,Отменен,0.00,г.Москва и Московская область,NaN
4,1062899,03.12.2019 21:43,NaN,Курс обучения «Эксперт»,Отменен,0.00,г.Москва и Московская область,NaN
...,...,...,...,...,...,...,...,...
287,1064720,30.12.2019 9:42,30.12.2019 12:49,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Завершен,2935.44,Самарская область,Яндекс.Касса
288,1064724,30.12.2019 11:32,NaN,Курс обучения «Консультант»,Отменен,0.00,NaN,NaN
289,1064775,31.12.2019 2:17,31.12.2019 2:22,Курс обучения «Консультант»,Завершен,7423.92,NaN,"Сбербанк эквайринг,Бонусный счет"
290,1064793,31.12.2019 16:40,01.01.2020 14:29,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Завершен,2935.44,Республика Карелия,Яндекс.Касса
291,1064796,31.12.2019 17:29,31.12.2019 17:32,Курс от Школы Диетологов. Повышение квалификац...,Завершен,9898.56,Уфа,"Сбербанк эквайринг,Бонусный счет"

In [16]:
df2 = pd.read_csv('../../lesson_2_data.csv', encoding='windows-1251', sep=';')
df2

,Номер,Дата создания,Дата оплаты,Title,Статус,Заработано,Город,Платежная система
0,1062823,01.12.2019 10:50,01.12.2019 10:52,Курс обучения «Эксперт»,Завершен,29597.50,Чита,Сбербанк эквайринг
1,1062855,01.12.2019 20:53,01.12.2019 21:27,Курс обучения «Эксперт»,Завершен,17450.30,Краснодар,Яндекс.Касса
2,1062856,01.12.2019 21:43,NaN,Курс обучения «Специалист»,Отменен,0.00,NaN,NaN
3,1062880,03.12.2019 0:18,NaN,Курс обучения «Консультант»,Отменен,0.00,г.Москва и Московская область,NaN
4,1062899,03.12.2019 21:43,NaN,Курс обучения «Эксперт»,Отменен,0.00,г.Москва и Московская область,NaN
...,...,...,...,...,...,...,...,...
287,1064720,30.12.2019 9:42,30.12.2019 12:49,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Завершен,2935.44,Самарская область,Яндекс.Касса
288,1064724,30.12.2019 11:32,NaN,Курс обучения «Консультант»,Отменен,0.00,NaN,NaN
289,1064775,31.12.2019 2:17,31.12.2019 2:22,Курс обучения «Консультант»,Завершен,7423.92,NaN,"Сбербанк эквайринг,Бонусный счет"
290,1064793,31.12.2019 16:40,01.01.2020 14:29,Подписка «ОНЛАЙН ДИЕТОЛОГ» с ежемесячным автос...,Завершен,2935.44,Республика Карелия,Яндекс.Касса
291,1064796,31.12.2019 17:29,31.12.2019 17:32,Курс от Школы Диетологов. Повышение квалификац...,Завершен,9898.56,Уфа,"Сбербанк эквайринг,Бонусный счет"

In [18]:
df3 = pd.read_csv('../../lesson_3_data.csv', encoding='windows-1251', sep=',')
df3

,Unnamed: 0,tk,pl,dia,hs,tc,cta,id_art,id_subsubfam,id_subfam,...,id_famn,id_seccion,id_subagr,id_agr,vta,uni,id_artn,art_sp,fam_sp,fam_en
0,1242,120071109002055793,1,2007/11/09,0.505729,110000761,11000076,21895,101070640100,1010706401,...,10107064,10107,101,1,0.68,1.0,21895,MARAVILLA 500 G Store_Brand,PASTA ALIMENTICIA SE,pasta
1,1243,120070601004053633,1,2007/06/01,0.588519,110000761,11000076,21816,101070640100,1010706401,...,10107064,10107,101,1,0.38,1.0,21816,FIDEO CABELLIN 500 G Store_Brand,PASTA ALIMENTICIA SE,pasta
2,1244,120070928004076410,1,2007/09/28,0.785498,28491841,2849184,562840,101070640100,1010706401,...,10107064,10107,101,1,1.55,2.0,562840,SPAGUETTI Nє 5 500 G Brand_1,PASTA ALIMENTICIA SE,pasta
3,1245,120070616003074261,1,2007/06/16,0.550961,95931501,9593150,28914,101070640100,1010706401,...,10107064,10107,101,1,1.03,2.0,28914,FIDEO FIDEUБ 500 Brand_7,PASTA ALIMENTICIA SE,pasta
4,1246,120070519001018477,1,2007/05/19,0.804954,93265591,9326559,159867,101070640100,1010706401,...,10107064,10107,101,1,1.09,1.0,159867,MACARRONES GRATINAR 5 Brand_2,PASTA ALIMENTICIA SE,pasta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48124,5142333,660820070702005033693,6608,2007/07/02,0.575660,45518841,4551884,22115,101070640100,1010706401,...,10107064,10107,101,1,0.71,1.0,22115,FIDEOS 0 500 G Brand_4,PASTA ALIMENTICIA SE,pasta
48125,5142335,660820070618006015969,6608,2007/06/18,0.829954,110824211,11082421,22124,101070640100,1010706401,...,10107064,10107,101,1,0.71,1.0,22124,PLUMAS 3 500 G Brand_4,PASTA ALIMENTICIA SE,pasta
48126,5150526,670120071110001433949,6701,2007/11/10,0.384120,1408670389,999860498,21818,101070640100,1010706401,...,10107064,10107,101,1,0.48,1.0,21818,MACARRONES 500 G Store_Brand,PASTA ALIMENTICIA SE,pasta
48127,5150527,670120071110001433949,6701,2007/11/10,0.384120,1408670389,999860498,21814,101070640100,1010706401,...,10107064,10107,101,1,0.48,1.0,21814,SPAGHETTI 500 G Store_Brand,PASTA ALIMENTICIA SE,pasta
48128,5150586,670220071001001404096,6702,2007/10/01,0.391262,48582221,4858222,21815,101070640100,1010706401,...,10107064,10107,101,1,1.36,2.0,21815,SPAGHETTINI 500 G Store_Brand,PASTA ALIMENTICIA SE,pasta