In [7]:
import pandas as pd
import numpy as np
from io import StringIO
from datetime import timedelta
from datetime import datetime
#import telegram

from airflow.decorators import dag, task
from airflow.operators.python import get_current_context

In [25]:
path2file = '/mnt/HC_Volume_18315164/home-jupyter/jupyter-a-burdin-23/DAGs/airflow/dags/a-burdin-23/vgsales.csv'

In [26]:
login = 'a-burdin-23'

In [27]:
year = 1994 + hash(f'{login}') % 23

In [28]:
default_args = {
    'owner': 'a.burdin',
    'depends_on_past': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
    'start_date': datetime(2022, 8, 23),
}

In [29]:
# @dag
# def answers4task(default_args=default_args, catchup=False):

In [30]:
def send_message(context):
    date = context['ds']
    dag_id = contex['dag'].dag_id
    message = f'Very good! Dag {dag_id} is completed on {date}.'
    bot = telegram.Bot(token=BOT_TOKEN)
    bot.send_message(chat_id = CHAT_ID, message = message)

In [31]:
#Считали и вернули таблицу
#@task()
def get_data():
    df = pd.read_csv(path2file)
    df = df.query("Year == @year")
    return df

In [32]:
get_data()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
46,47,Super Mario 64,N64,1996.0,Platform,Nintendo,6.91,2.85,1.91,0.23,11.89
63,64,Mario Kart 64,N64,1996.0,Racing,Nintendo,5.55,1.94,2.23,0.15,9.87
116,117,Crash Bandicoot,PS,1996.0,Platform,Sony Computer Entertainment,3.23,2.35,0.94,0.30,6.82
152,153,Tekken 2,PS,1996.0,Fighting,Sony Computer Entertainment,2.26,1.89,1.36,0.23,5.74
...,...,...,...,...,...,...,...,...,...,...,...
15301,15304,Brain Dead 13,PS,1996.0,Adventure,Coconuts Japan,0.01,0.01,0.00,0.00,0.02
15648,15651,Tail of the Sun,PS,1996.0,Role-Playing,ArtDink,0.01,0.01,0.00,0.00,0.02
15760,15763,Discworld II: Mortality Bytes!,PS,1996.0,Adventure,Psygnosis,0.01,0.01,0.00,0.00,0.02
16226,16229,Victory Spike,PS,1996.0,Sports,Imagineer,0.00,0.00,0.01,0.00,0.01
16373,16376,Meru Purana,PS,1996.0,Strategy,Gust,0.00,0.00,0.01,0.00,0.01

In [15]:
#Какая игра была самой продаваемой в этом году во всем мире?
    #Какая игра была самой продаваемой в этом году во всем мире?
@task()
def bestseller_game(df):
    bestseller_game_res = df.sort_values('Global_Sales', ascending=False).iloc[0].Name
    return bestseller_game_res

In [31]:
#Игры какого жанра были самыми продаваемыми в Европе? Перечислить все, если их несколько
#@task()
def bestseller_games_euro(df):
    result = df.groupby(["Genre"], as_index=False).agg({"EU_Sales":"sum"}).sort_values("EU_Sales", ascending=False)
    bestseller_games_euro_res = ', '.join(result.Genre.tolist())    
    return bestseller_games_euro_res

In [32]:
# На какой платформе было больше всего игр, которые продались более чем миллионным тиражом в Северной Америке?
# Перечислить все, если их несколько
#@task()
def million_platform_na(df):
    df['MoreThan1M'] = df.NA_Sales > 1.0
    million_platform_na_res = df.groupby(["Platform"], as_index=False)['NA_Sales'].agg({"MoreThan1M":"sum"}).sort_values("MoreThan1M", ascending=False)
    return million_platform_na_res

In [33]:
# У какого издателя самые высокие средние продажи в Японии?
# Перечислить все, если их несколько
#@task()
def best_publisher_jp(df):
    best_publisher_jp = df.groupby(["Publisher"], as_index=False).agg({"JP_Sales":"mean"}).sort_values("JP_Sales", ascending=False)
    best_publisher_jp_res = best_publisher_jp.query("JP_Sales > 0")
    return best_publisher_jp_res

In [34]:
# Сколько игр продались лучше в Европе, чем в Японии?
#@task()
def games_eur_vs_jp(df):
    df['EurMoreThanJp'] = df.EU_Sales > df.JP_Sales
    games_eur_vs_jp_res = df.EurMoreThanJp.count()
    return games_eur_vs_jp_res

In [55]:
#@task()
def print_data(bestseller_game_res, bestseller_games_euro_res, million_platform_na_res, best_publisher_jp_res, games_eur_vs_jp_res):
    
    date = year

    print(f' Какая игра была самой продаваемой в {date}г. во всем мире?')
    print(bestseller_game_res)
    print('----------------')
    print(f' Игры какого жанра были самыми продаваемыми в {date}г. в Европе?')
    print(bestseller_games_euro_res)
    print('----------------')
    print(f' На какой платформе было больше всего игр, которые продались более чем миллионным тиражом в {date}г. в Северной Америке?')
    print(million_platform_na_res)
    print('----------------')
    print(f' У какого издателя самые высокие средние продажи в Японии за {date}г.?')
    print(best_publisher_jp_res)
    print('----------------')
    print(f' Сколько игр продались лучше в Европе, чем в Японии за {date}г.?')
    print(games_eur_vs_jp_res)

In [56]:

# schedule_interval = '0 8 * * *'

# dag_burdin = DAG('burdin_28082022_2', default_args=default_args, schedule_interval=schedule_interval)

In [57]:
print_data(bestseller_game, bestseller_games_euro, million_platform_na, best_publisher_jp, games_eur_vs_jp)

 Какая игра была самой продаваемой в 2012 году во всем мире?
<function bestseller_game at 0x7fc54f374620>
----------------
 Игры какого жанра были самыми продаваемыми в 2012г. в Европе?
<function bestseller_games_euro at 0x7fc54f374488>
----------------
 На какой платформе было больше всего игр, которые продались более чем миллионным тиражом в 2012г. в Северной Америке?
<function million_platform_na at 0x7fc54f374268>
----------------
 У какого издателя самые высокие средние продажи в Японии за 2012?
<function best_publisher_jp at 0x7fc54f374378>
----------------
 Сколько игр продались лучше в Европе, чем в Японии за 2012г.?
<function games_eur_vs_jp at 0x7fc54f374510>